# Generated by Django 4.1.2 on 2022-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Sports', 'Sports'), ('Local', 'Local')], default='World', max_length=10),
        ),
    ]
